service: aws-node-rest-api-mongodb

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
